import { images } from "../Cards/realizedCardImages.ts";


const realizedCardData = [
    {
        id: 1,
        mainImage: images.OrechRosh,
        images: [images.OrechRosh],
        text: "Орехова роща",
        title:'',
    },
    {
        id: 2,
        mainImage: images.Shepkin,
        images: [images.Shepkin, images.Shepkin_2],
        text: "поселок Щепкин",
        title:'',
    },
    {
        id: 3,
        mainImage: images.Eremenkin,
        images: [images.Eremenkin, images.Eremenkin_2, images.Eremenkin_3],
        text: "Еременко",
        title:'',
    },
    {
        id: 4,
        mainImage: images.Shepkins,
        images: [images.Shepkins, images.Shepkins_2, images.Shepkins_3, images.Shepkins_4, images.Shepkins_5, images.Shepkins_6,],
        text: "80 м^2",
        title:'',
    },
    {
        id: 5,
        mainImage: images.Chaltir,
        images: [images.Chaltir],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 6,
        mainImage: images.Rossiski,
        images: [images.Rossiski],
        text: "Поселок Российский",
        title:'',
    },
    {
        id: 7,
        mainImage: images.Kamisheha,
        images: [images.Kamisheha,images.Kamisheha_2],
        text: "Поселок Камышеваха",
        title:'',
    },
    {
        id: 8,
        mainImage: images.Chaltirs,
        images: [images.Chaltirs, images.Chaltirs_2, images.Chaltirs_3, images.Chaltirs_4],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 9,
        mainImage: images.Kamishehs,
        images: [images.Kamishehs],
        text: "Поселок Камышеваха",
        title:'',
    },
    {
        id: 10,
        mainImage: images.ChaltirId3,
        images: [images.ChaltirId3],
        text: "Чалтырь",
        title:'',

    },
    {
        id: 11,
        mainImage: images.Leninakan,
        images: [images.Leninakan,images.Leninakan_2,images.Leninakan_3],
        text: "Ленинакан",
        title:'',
    },
    {
        id: 12,
        mainImage: images.RedKrim,
        images: [images.RedKrim,images.RedKrim_2,images.RedKrim_3],
        text: "Красный Крым",
        title:'',
    },
    {
        id: 13,
        mainImage: images.Leninavan,
        images: [images.Leninavan, images.Leninavan_2, images.Leninavan_3, images.Leninavan_4,],
        text: "Ленинаван",
        title:'',
    },
    {
        id: 14,
        mainImage: images.ChaltirId4,
        images: [images.ChaltirId4,images.ChaltirId4_2,],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 15,
        mainImage: images.ChaltirId5,
        images: [images.ChaltirId5,],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 16,
        mainImage: images.ChaltirId6,
        images: [images.ChaltirId6],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 17,
        mainImage: images.ChaltirId7,
        images: [images.ChaltirId7, images.ChaltirId7_2, images.ChaltirId7_3, images.ChaltirId7_4, images.ChaltirId7_5],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 18,
        mainImage: images.Rostov_on_Don,
        images: [images.Rostov_on_Don, images.Rostov_on_Don_2, images.Rostov_on_Don_3, images.Rostov_on_Don_4,],
        text: "Ростов-на-Дону",
        title:'',
    },
    {
        id: 19,
        mainImage: images.Olginskaya,
        images: [images.Olginskaya, images.Olginskaya_2],
        text: "Ольгинская",
        title:'',
    },
    {
        id: 20,
        mainImage: images.OlginskayaId2,
        images: [images.OlginskayaId2, images.OlginskayaId2_2, images.OlginskayaId2_3],
        text: "Ольгинская",
        title:'',
    },
    {
        id: 21,
        mainImage: images.ChaltirId8,
        images: [images.ChaltirId8, images.ChaltirId8_2, images.ChaltirId8_3, images.ChaltirId8_4,],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 22,
        mainImage: images.ChaltirId9,
        images: [images.ChaltirId9, images.ChaltirId9_2, images.ChaltirId9_3, images.ChaltirId9_4,],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 23,
        mainImage: images.Bataiysk,
        images: [images.Bataiysk, images.Bataiysk_2],
        text: "Батайск",
        title:'',
    },
    {
        id: 24,
        mainImage: images.OrechRoshId2,
        images: [images.OrechRoshId2, images.OrechRoshId2_2, images.OrechRoshId2_3, images.OrechRoshId2_4, images.OrechRoshId2_5, images.OrechRoshId2_6,],
        text: "Ореховая роща",
        title:'',
    },
    {
        id: 25,
        mainImage: images.OrechRoshId3,
        images: [images.OrechRoshId3, images.OrechRoshId3_2, images.OrechRoshId3_3],
        text: "Ореховая роща",
        title:'',
    },
    {
        id: 26,
        mainImage: images.OrechRoshId4,
        images: [images.OrechRoshId4, images.OrechRoshId4_2, images.OrechRoshId4_3, images.OrechRoshId4_4,
                 images.OrechRoshId4_5, images.OrechRoshId4_6, images.OrechRoshId4_7, images.OrechRoshId4_8,
                 images.OrechRoshId4_9, images.OrechRoshId4_10, images.OrechRoshId4_11, images.OrechRoshId4_12],
        text: "Ореховая роща",
        title:'',
    },
    {
        id: 27,
        mainImage: images.OlginskayaId3,
        images: [images.OlginskayaId3, images.OlginskayaId3_2, images.OlginskayaId3_3],
        text: "Ольгинская",
        title:'',
    },
    {
        id: 28,
        mainImage: images.ChaltirId10,
        images: [images.ChaltirId10, images.ChaltirId10_2],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 29,
        mainImage: images.ChaltirId11,
        images: [images.ChaltirId11, images.ChaltirId11_2],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 30,
        mainImage: images.ChaltirId12,
        images: [images.ChaltirId12],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 31,
        mainImage: images.ChaltirId13,
        images: [images.ChaltirId13,images.ChaltirId13_2],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 32,
        mainImage: images.ChaltirId14,
        images: [images.ChaltirId14],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 33,
        mainImage: images.ChaltirId15,
        images: [images.ChaltirId15,images.ChaltirId15_2,images.ChaltirId15_3,images.ChaltirId15_4,images.ChaltirId15_5],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 34,
        mainImage: images.ChaltirId16,
        images: [images.ChaltirId16],
        text: "Чалтырь",
        title:'',
    },
    {
        id: 35,
        mainImage: images.LeninakanId2,
        images: [images.LeninakanId2],
        text: "Ленинакан",
        title:'',
    },
    {
        id: 36,
        mainImage: images.LeninakanId3,
        images: [images.LeninakanId3],
        text: "Ленинакан",
        title:'',
    },
    {
        id: 37,
        mainImage: images.LeninakanId4,
        images: [images.LeninakanId4, images.LeninakanId4_2],
        text: "Ленинакан",
        title:'',
    },
    {
        id: 38,
        mainImage: images.LeninakanId5,
        images: [images.LeninakanId5,images.LeninakanId5_2],
        text: "Ленинакан",
        title:'',
    },
    {
        id: 39,
        mainImage: images.LeninakanId6,
        images: [images.LeninakanId6, images.LeninakanId6_2, images.LeninakanId6_3, images.LeninakanId6_4],
        text: "Ленинакан",
        title:'',
    },
    {
        id: 40,
        mainImage: images.LeninavanId2,
        images: [images.LeninavanId2, images.LeninavanId2_2],
        text: "Ленинаван",
        title:'',
    },
    {
        id: 41,
        mainImage: images.LeninakanId7,
        images: [images.LeninakanId7, images.LeninakanId7_2],
        text: "Ленинакан",
        title:'',
    },
];

export default realizedCardData;